POST http://localhost:3000/reports
Content-Type: application/json

{
    "make": "Mercedes", 
    "model": "Corolla", 
    "year": 1988, 
    "milage": 10000, 
    "lng": 0, 
    "lat": 0, 
    "price": 500000
}

### Get Report By Id 2
GET http://localhost:3000/reports
